### ISSUE TITLE
using accelerometer sleep data

### ISSUE THREAD

**Issue by sarmadm** [informaton/padaco#66]
Hi

How can I use this software ? what is the type of data needed ? and what output can I get from it ?

Thanks

**Comment by informaton** [comment]
Hi,

Currently, it uses Actigraph accelerometer data and has been tested specifically with Actigraph's GT3X+ sensor.  You can use the software to visualize the sensor data, which includes tri-axial accelerometry (X,Y,Z axis and their vector magnitude), luminance, and some other derived measures (e.g. step count and inclination).  

Check out the home page at http://web.stanford.edu/~hyatt4/software/padaco for a user manual, test data set, and compiled versions of the software (Mac OS X only at the moment).  

If you want to run the source code from here, then you will need to use MATLAB.

The software provides several visualizations of the data and clustering features when you have many days of recorded activity.  There is an activity and sleep classification algorithm as well, which is described in the help section of the software.
