### ISSUE TITLE
Error in PABatchTool/disable (line 37)

### ISSUE THREAD

**Issue by sarmadm** [informaton/padaco#70]
HI

When I try batch processing this error is displayed :  

Undefined function or variable 'disablehandles'.

Error in PABatchTool/disable (line 37)
            disablehandles(this.figureH);

Error in PABatchTool/startBatchProcessCallback (line 358)
            this.disable();

Error in PABatchTool>@(varargin)this.startBatchProcessCallback(varargin{:}) (line 119)
            set(this.handles.button_go,'callback',@this.startBatchProcessCallback);
 
Error while evaluating UIControl Callback

**Comment by informaton** [comment]
This issue was created by recent code base reorganization which utilized symbolically links to a separate library.  The links need to be updated with a git submodule or some other reference mechanism instead.  

This needs to be done soon.  The issue remains open.

**Comment by informaton** [comment]
Most recent commit addresses.  Please try again.  The error message here looks like there may be a path issue.  You can check this by restarting Padaco and trying again.
